---
kind: pipeline
type: docker
name: default

steps:
- name: eldev-version
  image: silex/emacs:27.1-dev
  commands:
  - eldev -dvtQ --version || true
- name: build
  image: silex/emacs:27.1-dev
  commands:
  - eldev -dvtQ build
- name: lint
  image: silex/emacs:27.1-dev
  commands:
  - eldev -dvtQ lint
